<?php
namespace App\Controllers\administrator;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/

use App\Models\Admin_model;
use App\Controllers\BaseController;
use App\Models\Deliver_model;
use App\Models\Master_model;

class Dashboard extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new Admin_model(); //Set Default Models Of this Controller
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    // This event executed after constructor
    protected function onLoad(){
        $this->PageData->parent = "administrator/Admin";
        $this->PageData->header = (session()->has("level") ? NULL : ucfirst(str_replace("_", '', session("level"))) . " :: ") . 'Admin';
        $this->PageData->access = ["administrator"];
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", 'Login session outdate. Please re-Login !');
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'administrator/_templates/Container',
            'header' => 'administrator/_templates/header',
            'navbar' => 'administrator/_templates/navbar',
            'sidebar' => 'administrator/_templates/sidebar',
            'footer' => 'administrator/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index()
    {
        $master = new Master_model();
        $deliver = new Deliver_model();
        $c = $master->select("COUNT(resi) AS c")->join("pickup", "master.id_pickup=pickup.id", "LEFT")->where("master.status", 0)->where("pickup.status = 1", NULL, FALSE)->first()->c;
        $dc = $deliver->select("COUNT(resi) AS c")->where("status", -1)->first()->c;
        $ds = $deliver->select("COUNT(resi) AS c")->where("valid", 0)->first()->c;
        session()->set("verivikasi", $c);
        session()->set("d_cancel", $dc);
        session()->set("d_success", $ds);
        $data = [
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('administrator/home', $data);
        //endindex
    }
    //ENDFUNCTION
}
