<?php
namespace App\Controllers\Administrator;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/

use App\Controllers\BaseController;
use App\Models\Jenissimpan_pinjam_model;
use App\Models\Kelola_nasabah_model;
use App\Models\Tambah_pinjaman_model;
use App\Models\Tambah_simpanan_model;
use App\Models\User_model;

class Dashboard extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new User_model(); //Set Default Models Of this Controller
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    // This event executed after constructor
    protected function onLoad()
    {
        $this->PageData->access = ["Administrator", "Pimpinan"];
        $this->PageData->parent = "Administrator/Dashboard";
        $this->PageData->header = (!session()->has("hak_akses") ? NULL : ucfirst(str_replace("_", '', session("hak_akses"))) . " :: ") . 'Dashboard';
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", 'Login session outdate. Please re-Login !');
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'Administrator/_templates/Container',
            'header' => 'Administrator/_templates/header',
            'navbar' => 'Administrator/_templates/navbar',
            'sidebar' => 'Administrator/_templates/sidebar',
            'footer' => 'Administrator/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index()
    {
        $nasabah = new Kelola_nasabah_model();
        $jenis = new Jenissimpan_pinjam_model();
        
        $incash = 0;
        $n = $nasabah->findAll();
        foreach ($n as $key => $value) {
            $j = $jenis->getById($value->id_jenissimpanpinjam);
            $bunga = (isset($j->bunga_simpanan)? $j->bunga_simpanan:0);
            $incash += $this->hitung_saldo_nasabah($value->id_nasabah, $bunga);
        }
        session()->set("incash", $incash);

        $data = [
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('Administrator/home', $data);
        //endindex
    }
    //ENDFUNCTION
}
